from enum import StrEnum


class InternalEvidenceType(StrEnum):
    """Evidence kinds the independent analysis layer may interpret."""

    GITHUB_STATIC = "GITHUB_STATIC"
    GITHUB_ACTIVITY = "GITHUB_ACTIVITY"
    CODE_EVIDENCE = "CODE_EVIDENCE"
    BACKEND_DERIVED = "BACKEND_DERIVED"


class AnalysisDepth(StrEnum):
    """Available evidence depths, not scores of repository quality."""

    P0 = "P0"
    P1 = "P1"
    P2 = "P2"


class EvidenceValueType(StrEnum):
    """Semantic type of an evidence value supplied by the backend."""

    STRING = "STRING"
    BOOLEAN = "BOOLEAN"
    INTEGER = "INTEGER"
    DECIMAL = "DECIMAL"
    STRING_LIST = "STRING_LIST"


class SnapshotHashAlgorithm(StrEnum):
    """Hash algorithm used to identify a repository snapshot."""

    SHA1 = "SHA1"
    SHA256 = "SHA256"


class AnalysisItemType(StrEnum):
    """Semantic roles of grounded items generated by the analysis pipeline."""

    OBSERVATION = "OBSERVATION"
    INTERPRETATION = "INTERPRETATION"
    RECOMMENDATION = "RECOMMENDATION"
    JOB_APPEAL = "JOB_APPEAL"


class PortfolioStatementType(StrEnum):
    """Intended usage of one generated portfolio statement."""

    RESUME = "RESUME"
    PORTFOLIO = "PORTFOLIO"
    INTERVIEW = "INTERVIEW"


class EvidenceConfidence(StrEnum):
    """Directness and scope of evidence, not probability of user ability."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_VERIFIABLE = "NOT_VERIFIABLE"


class RecommendationPriority(StrEnum):
    """Relative order in which a recommendation should be addressed."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class InternalGenerationStage(StrEnum):
    """LLM generation stages recorded by the internal analysis pipeline."""

    REPOSITORY = "REPOSITORY"
    PORTFOLIO = "PORTFOLIO"
    INTERVIEW = "INTERVIEW"
    STATEMENT = "STATEMENT"
