from enum import StrEnum


class InternalEvidenceType(StrEnum):
    """Evidence kinds the independent P0 analysis layer may interpret."""

    GITHUB_STATIC = "GITHUB_STATIC"
    BACKEND_DERIVED = "BACKEND_DERIVED"


class AnalysisDepth(StrEnum):
    """Analysis depths currently supported by the internal pipeline."""

    P0 = "P0"


class AnalysisItemType(StrEnum):
    """Semantic roles of grounded items generated by the analysis pipeline."""

    OBSERVATION = "OBSERVATION"
    INTERPRETATION = "INTERPRETATION"
    RECOMMENDATION = "RECOMMENDATION"
    JOB_APPEAL = "JOB_APPEAL"


class PortfolioStatementType(StrEnum):
    """Intended usage of one generated portfolio statement."""

    RESUME = "RESUME"
    PORTFOLIO = "PORTFOLIO"
    INTERVIEW = "INTERVIEW"


class EvidenceConfidence(StrEnum):
    """Directness and scope of evidence, not probability of user ability."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_VERIFIABLE = "NOT_VERIFIABLE"


class RecommendationPriority(StrEnum):
    """Relative order in which a recommendation should be addressed."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class InternalGenerationStage(StrEnum):
    """LLM generation stages recorded by the internal analysis pipeline."""

    REPOSITORY = "REPOSITORY"
    PORTFOLIO = "PORTFOLIO"
    INTERVIEW = "INTERVIEW"
